'use client';

import React, { useState, useMemo } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { useAppStore } from '@/lib/store';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { ApprovalInstance, ApprovalStatus } from '@/types';
import { 
  Map, 
  Filter, 
  Search, 
  GitFork, 
  FileText, 
  Clock, 
  Building, 
  CheckCircle2, 
  AlertCircle, 
  ArrowRight, 
  ExternalLink,
  Info,
  ChevronDown,
  ChevronUp,
  X
} from 'lucide-react';

function ApprovalRoadmapContent() {
  const searchParams = useSearchParams();
  const initialSearch = searchParams.get('search') || '';

  const { approvals, businessProfile, updateApprovalStatus } = useAppStore();

  const [activeFilter, setActiveFilter] = useState<'All' | ApprovalStatus>('All');
  const [searchQuery, setSearchQuery] = useState(initialSearch);
  const [selectedApproval, setSelectedApproval] = useState<ApprovalInstance | null>(null);

  const completedCount = approvals.filter(a => a.status === 'Completed').length;
  const inProgressCount = approvals.filter(a => a.status === 'In Progress').length;
  const actionRequiredCount = approvals.filter(a => a.status === 'Action Required').length;

  const filteredApprovals = useMemo(() => {
    return approvals.filter(app => {
      // Filter by status
      if (activeFilter !== 'All' && app.status !== activeFilter) {
        return false;
      }
      // Filter by query
      if (searchQuery.trim()) {
        const q = searchQuery.toLowerCase();
        const matchesName = app.approvalName.toLowerCase().includes(q);
        const matchesAuth = app.authority.toLowerCase().includes(q);
        const matchesCode = app.approvalCode.toLowerCase().includes(q);
        const matchesDocs = app.requiredDocuments.some(d => d.toLowerCase().includes(q));
        if (!matchesName && !matchesAuth && !matchesCode && !matchesDocs) return false;
      }
      return true;
    });
  }, [approvals, activeFilter, searchQuery]);

  return (
    <div className="space-y-6 pb-12">
      {/* Header and Context */}
      <div className="bg-white border border-[#D9E1E8] rounded p-5 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-bold text-[#17324D]">Your Personalized Approval Roadmap</h1>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#edf4fa] text-[#1F4E79] border border-[#c8dced] font-bold">
              MAITRI COMPLIANT
            </span>
          </div>
          <p className="text-xs text-[#667085] mt-1">
            Statutory clearances required for <strong className="text-[#17202A]">{businessProfile.businessName}</strong> ({businessProfile.industry}) in {businessProfile.district}.
          </p>

          <div className="flex flex-wrap items-center gap-3 mt-3 text-xs">
            <span className="font-semibold text-[#17324D]">{approvals.length} Applicable Approvals</span>
            <span className="text-[#D9E1E8]">•</span>
            <span className="text-[#16855b] font-medium">{completedCount} Completed</span>
            <span className="text-[#D9E1E8]">•</span>
            <span className="text-[#1F4E79] font-medium">{inProgressCount} In Progress</span>
            <span className="text-[#D9E1E8]">•</span>
            <span className="text-[#c06c1c] font-medium">{actionRequiredCount} Action Required</span>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <Link
            href="/entrepreneur/dependency-graph"
            className="px-3.5 py-2 rounded text-xs font-semibold bg-[#edf4fa] hover:bg-[#dfeaf4] text-[#1F4E79] border border-[#c8dced] transition-colors flex items-center gap-1.5"
          >
            <GitFork className="w-3.5 h-3.5" />
            <span>Dependency Graph</span>
          </Link>
          <Link
            href="/entrepreneur/business-profile"
            className="px-3 py-2 rounded text-xs font-semibold bg-white hover:bg-[#F5F7FA] text-[#344054] border border-[#D9E1E8] transition-colors"
          >
            Re-evaluate Profile
          </Link>
        </div>
      </div>

      {/* Legal & Regulatory Rigor Disclaimer Banner */}
      <div className="bg-[#edf4fa] border border-[#c8dced] rounded p-3 text-xs text-[#1F4E79] flex items-start gap-2.5">
        <Info className="w-4 h-4 shrink-0 mt-0.5 text-[#1F4E79]" />
        <div className="leading-snug">
          <strong>Deterministic Regulatory Model:</strong> Clearances below are generated by evaluating your enterprise parameters against the Water/Air Acts, Maharashtra Factories Rules 1963, and Fire Services Act 2006. Verify final requirements with the respective competent department portals.
        </div>
      </div>

      {/* Filter Tabs and Search Bar */}
      <div className="bg-white border border-[#D9E1E8] rounded p-3 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        {/* Status Filter Buttons */}
        <div className="flex flex-wrap items-center gap-1.5 text-xs">
          {(['All', 'Action Required', 'In Progress', 'Completed'] as const).map(filter => (
            <button
              key={filter}
              onClick={() => setActiveFilter(filter as any)}
              className={`px-3 py-1.5 rounded transition-colors ${
                activeFilter === filter
                  ? 'bg-[#1F4E79] text-white font-bold'
                  : 'bg-[#F5F7FA] hover:bg-[#edf2f7] text-[#344054] font-medium'
              }`}
            >
              {filter}
              {filter === 'Action Required' && actionRequiredCount > 0 && (
                <span className="ml-1.5 px-1.5 py-0.2 rounded-full text-[10px] bg-[#c93636] text-white font-bold">
                  {actionRequiredCount}
                </span>
              )}
            </button>
          ))}
        </div>

        {/* Search Input */}
        <div className="relative min-w-[240px]">
          <Search className="w-3.5 h-3.5 text-[#667085] absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
          <input
            type="text"
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            placeholder="Filter approvals or documents..."
            className="w-full pl-8 pr-3 py-1.5 text-xs bg-[#F5F7FA] border border-[#D9E1E8] rounded text-[#17202A] focus:outline-none focus:border-[#1F4E79]"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      </div>

      {/* APPROVALS LIST CARDS */}
      <div className="space-y-4">
        {filteredApprovals.length === 0 ? (
          <div className="bg-white border border-[#D9E1E8] rounded p-12 text-center text-xs text-[#667085]">
            <p className="font-semibold text-sm text-[#17202A]">No approvals matching your current filter.</p>
            <p className="mt-1">Try resetting the filter tabs or adjusting your search keyword.</p>
            <button
              onClick={() => { setActiveFilter('All'); setSearchQuery(''); }}
              className="mt-3 px-3 py-1.5 rounded bg-[#1F4E79] text-white font-medium text-xs"
            >
              Reset Filters
            </button>
          </div>
        ) : (
          filteredApprovals.map(app => (
            <div
              key={app.id}
              className={`bg-white border rounded shadow-xs p-5 transition-all ${
                app.status === 'Action Required'
                  ? 'border-l-4 border-l-[#d9822b] border-[#D9E1E8]'
                  : 'border-[#D9E1E8] hover:border-[#b8c9d9]'
              }`}
            >
              <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4">
                
                {/* Main Approval Info */}
                <div className="space-y-2 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="text-sm font-bold text-[#17324D]">{app.approvalName}</h2>
                    <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-[#F5F7FA] text-[#475467] border border-[#D9E1E8]">
                      {app.approvalCode}
                    </span>
                    <StatusBadge status={app.status} />
                    <span
                      className={`text-[10px] font-bold px-1.5 py-0.2 rounded uppercase ${
                        app.priority === 'High'
                          ? 'bg-rose-50 text-rose-700 border border-rose-200'
                          : 'bg-slate-100 text-slate-700'
                      }`}
                    >
                      {app.priority} Priority
                    </span>
                  </div>

                  <p className="text-xs text-[#475467] font-medium flex items-center gap-1.5">
                    <Building className="w-3.5 h-3.5 text-[#1F4E79]" />
                    <span><strong>Authority:</strong> {app.authority} ({app.department})</span>
                  </p>

                  {/* Why it applies callout */}
                  <div className="p-3 rounded bg-[#F5F7FA] border border-[#D9E1E8] text-xs">
                    <p className="text-[#344054] leading-relaxed">
                      <strong className="text-[#17324D]">Why this applies:</strong> {app.whyApplies}
                    </p>
                    <p className="text-[11px] text-[#667085] mt-1 flex items-center gap-2">
                      <span>Source: <em>{app.source}</em></span>
                      <span>•</span>
                      <span>Legal Reference: <code>{app.legalReference}</code></span>
                    </p>
                  </div>

                  {/* Action Required Alert Box if present */}
                  {app.status === 'Action Required' && (
                    <div className="p-3 rounded bg-[#fdfaf5] border border-[#f6deb9] text-xs text-[#c06c1c] flex items-start gap-2">
                      <AlertCircle className="w-4 h-4 shrink-0 mt-0.5 text-[#d9822b]" />
                      <div>
                        <strong>Action Required:</strong> {app.actionRequiredMessage}
                      </div>
                    </div>
                  )}

                  {/* Documents Required */}
                  <div className="text-xs text-[#344054] pt-1">
                    <span className="font-semibold text-[#17202A]">Required Documents:</span>
                    <div className="flex flex-wrap gap-1.5 mt-1">
                      {app.requiredDocuments.map((doc, idx) => (
                        <span
                          key={idx}
                          className="px-2 py-0.5 rounded bg-white border border-[#D9E1E8] text-[11px] text-[#475467]"
                        >
                          {doc}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Dependencies if any */}
                  {app.dependencies.length > 0 && (
                    <div className="text-xs text-[#667085] pt-1 flex items-center gap-2">
                      <GitFork className="w-3.5 h-3.5 text-[#1F4E79]" />
                      <span>
                        Prerequisite Dependencies: <strong>{app.dependencies.join(', ')}</strong>
                      </span>
                    </div>
                  )}
                </div>

                {/* Right Column: Timeline & Action CTAs */}
                <div className="lg:w-56 shrink-0 flex flex-col justify-between border-t lg:border-t-0 lg:border-l border-[#D9E1E8] pt-3 lg:pt-0 lg:pl-4 space-y-3">
                  <div>
                    <span className="text-[10px] font-bold text-[#667085] uppercase tracking-wider block">
                      Estimated SLA Timeline
                    </span>
                    <div className="flex items-center gap-1.5 mt-1 text-[#17324D] font-bold text-sm">
                      <Clock className="w-4 h-4 text-[#1F4E79]" />
                      <span>{app.estimatedTimelineDays} Days</span>
                    </div>
                    {app.submissionDate && (
                      <p className="text-[10px] text-[#667085] mt-0.5">
                        Submitted: {app.submissionDate}
                      </p>
                    )}
                  </div>

                  <div className="space-y-2">
                    <button
                      onClick={() => setSelectedApproval(app)}
                      className="w-full py-1.5 px-3 rounded text-xs font-semibold bg-[#F5F7FA] hover:bg-[#edf2f7] text-[#1F4E79] border border-[#D9E1E8] transition-colors text-center block"
                    >
                      View Approval Details
                    </button>

                    {app.status === 'Action Required' && (
                      <Link
                        href={app.approvalCode === 'FIRE-NOC' ? '/entrepreneur/applications' : '/entrepreneur/documents'}
                        className="w-full py-1.5 px-3 rounded text-xs font-semibold bg-[#1F4E79] hover:bg-[#17324D] text-white text-center block transition-colors"
                      >
                        Resolve Requirement
                      </Link>
                    )}

                    {app.status === 'Completed' && (
                      <div className="text-[11px] text-emerald-700 font-medium flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                        <span>Completed on {app.completedDate || 'Aug 2026'}</span>
                      </div>
                    )}
                  </div>
                </div>

              </div>
            </div>
          ))
        )}
      </div>

      {/* APPROVAL DETAILS MODAL */}
      {selectedApproval && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-2xs z-50 flex items-center justify-center p-4">
          <div className="w-full max-w-2xl bg-white border border-[#D9E1E8] rounded shadow-2xl p-6 space-y-4 max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between pb-3 border-b border-[#D9E1E8]">
              <div>
                <h3 className="text-base font-bold text-[#17324D]">{selectedApproval.approvalName}</h3>
                <p className="text-xs text-[#667085]">{selectedApproval.authority}</p>
              </div>
              <button
                onClick={() => setSelectedApproval(null)}
                className="p-1 rounded text-slate-400 hover:text-slate-600"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div className="grid grid-cols-2 gap-3 p-3 bg-[#F5F7FA] rounded border border-[#D9E1E8]">
                <div>
                  <span className="text-[#667085]">Status:</span>
                  <div className="mt-0.5"><StatusBadge status={selectedApproval.status} /></div>
                </div>
                <div>
                  <span className="text-[#667085]">Statutory Timeline:</span>
                  <p className="font-bold text-[#17202A] mt-0.5">{selectedApproval.estimatedTimelineDays} Days</p>
                </div>
                <div>
                  <span className="text-[#667085]">Regulatory Department:</span>
                  <p className="font-bold text-[#17202A] mt-0.5">{selectedApproval.department}</p>
                </div>
                <div>
                  <span className="text-[#667085]">Legal Enactment:</span>
                  <p className="font-bold text-[#17202A] mt-0.5">{selectedApproval.legalReference}</p>
                </div>
              </div>

              {/* 6-Stage Process Timeline */}
              <div className="pt-2">
                <span className="font-bold text-xs text-[#17324D] uppercase tracking-wider block mb-2">
                  Official Statutory Clearance Flow
                </span>
                <div className="grid grid-cols-6 gap-1 text-center text-[10px]">
                  {[
                    { num: 1, label: 'Document Prep', done: true },
                    { num: 2, label: 'Submission', done: selectedApproval.status !== 'Upcoming' },
                    { num: 3, label: 'Scrutiny', done: ['In Progress', 'Completed'].includes(selectedApproval.status) },
                    { num: 4, label: 'Site Inspection', done: selectedApproval.status === 'Completed' },
                    { num: 5, label: 'Clarifications', done: selectedApproval.status === 'Completed' },
                    { num: 6, label: 'Formal Sanction', done: selectedApproval.status === 'Completed' },
                  ].map(step => (
                    <div
                      key={step.num}
                      className={`p-2 rounded border ${
                        step.done ? 'bg-emerald-50 border-emerald-200 text-emerald-800 font-bold' : 'bg-slate-50 border-slate-200 text-slate-400'
                      }`}
                    >
                      <div className="text-xs mb-0.5">{step.num}</div>
                      <div className="leading-tight truncate">{step.label}</div>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <strong className="text-[#17202A]">Why Applicable to this Enterprise:</strong>
                <p className="text-[#475467] mt-1 leading-relaxed">{selectedApproval.whyApplies}</p>
              </div>

              <div>
                <strong className="text-[#17202A]">Mandatory Submission Documents:</strong>
                <ul className="list-disc pl-5 mt-1 space-y-1 text-[#475467]">
                  {selectedApproval.requiredDocuments.map((d, i) => (
                    <li key={i}>{d}</li>
                  ))}
                </ul>
              </div>

              <div className="p-3 bg-[#edf4fa] border border-[#c8dced] rounded text-[11px] text-[#1F4E79]">
                <strong>Prototype Notice:</strong> All requirements are generated dynamically from the UdyamSetu deterministic rule engine.
              </div>
            </div>

            <div className="pt-3 border-t border-[#D9E1E8] flex items-center justify-between">
              <button
                type="button"
                onClick={() => setSelectedApproval(null)}
                className="px-4 py-2 rounded bg-[#F5F7FA] hover:bg-[#edf2f7] text-[#344054] text-xs font-semibold border border-[#D9E1E8]"
              >
                Close Window
              </button>

              <Link
                href="/entrepreneur/documents"
                className="px-4 py-2 rounded bg-[#1F4E79] hover:bg-[#17324D] text-white text-xs font-semibold flex items-center gap-1.5"
              >
                <span>Upload Documents for this Approval</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function ApprovalRoadmapPage() {
  return (
    <React.Suspense fallback={<div className="p-8 text-center text-xs text-[#667085]">Loading Approval Roadmap...</div>}>
      <ApprovalRoadmapContent />
    </React.Suspense>
  );
}
